/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fees.view;
import javax.swing.JOptionPane;
import org.fees.model.Student;
import org.fees.controller.StudentDAO;
/**
 *
 * @author DELL
 */
public class UpgradeClass extends javax.swing.JInternalFrame {
private int grade;
private double due;
    /**
     * Creates new form UpgradeClass
     */
    public UpgradeClass() {
        initComponents();
        fillData();
    }
public void fillData()
{
    jTextField_Due.setText("0.0");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_One = new javax.swing.JRadioButton();
        jButton_Upgrade = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Due = new javax.swing.JTextField();

        setClosable(true);
        setTitle("UpgradeClass");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Upgrade All Student XI Class To ");

        jRadioButton_One.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jRadioButton_One.setSelected(true);
        jRadioButton_One.setText("XII");
        jRadioButton_One.setEnabled(false);
        jRadioButton_One.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton_OneItemStateChanged(evt);
            }
        });
        jRadioButton_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_OneActionPerformed(evt);
            }
        });

        jButton_Upgrade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_Upgrade.setText("Upgrade");
        jButton_Upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpgradeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Due For XII Class                    Rs");

        jTextField_Due.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField_Due.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_Due.setText("0.0");
        jTextField_Due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DueActionPerformed(evt);
            }
        });
        jTextField_Due.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DueKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Upgrade, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jRadioButton_One)
                    .addComponent(jTextField_Due))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton_One, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField_Due))
                .addGap(18, 18, 18)
                .addComponent(jButton_Upgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_UpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpgradeActionPerformed
        due=Double.parseDouble(jTextField_Due.getText());
                        grade=12;

                        if(due<=0)
                        {
                                                          JOptionPane.showMessageDialog(null,"Enter Due Amount");

                        }
        else
        {
     Student s=new Student();
s.setGrade(grade);
s.setDue(due);
StudentDAO sdao=new StudentDAO();
int count=sdao.updateClass(s);
if(count>0)
{
              JOptionPane.showMessageDialog(null,"Upgrade Sucessfull");
               fillData();

             
}
else{
                  JOptionPane.showMessageDialog(null,"Unsucessfull");

}
        }
     

    }//GEN-LAST:event_jButton_UpgradeActionPerformed

    private void jTextField_DueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DueKeyTyped
char ch=evt.getKeyChar();
if(!(ch>='0' && ch<='9'))
{
    evt.consume();
}


    }//GEN-LAST:event_jTextField_DueKeyTyped

    private void jRadioButton_OneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton_OneItemStateChanged
  
     

    }//GEN-LAST:event_jRadioButton_OneItemStateChanged

    private void jRadioButton_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_OneActionPerformed

    }//GEN-LAST:event_jRadioButton_OneActionPerformed

    private void jTextField_DueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Upgrade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_One;
    private javax.swing.JTextField jTextField_Due;
    // End of variables declaration//GEN-END:variables
}
